name: road_mechanic
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_riverpod: ^2.3.4
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.1
  flutter_zoom_drawer: ^3.0.4+1
  intl: ^0.17.0
  geolocator: ^9.0.2
  html: ^0.15.2
  url_launcher: ^6.1.10
  map: ^1.4.1
  latlong2: ^0.8.1
  flutter_dotenv: ^5.0.2
  flutter_map: ^0.14.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

   
  assets:
    - .env
    - images/
  
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf
           style: italic
 