name: monide
description: Find out if ATMs are working.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_zoom_drawer: ^3.0.4+1
  intl: ^0.20.2
  geolocator: ^10.1.0
  html: ^0.15.2
  url_launcher: ^6.1.10
  map: ^2.0.2
  latlong2: ^0.9.1
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

 
  uses-material-design: true

   
  assets:
    
    # - .env
    - images/
  
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf
           style: italic
 